export const allowedItems: Record<
  number,
  { itemId: number; name?: string; vendorSellPrice?: number }
> = {
  0: { name: "Spruce log", itemId: 0, vendorSellPrice: 6 },
  1: { name: "Pine log", itemId: 1, vendorSellPrice: 10 },
  2: { name: "Chestnut log", itemId: 2, vendorSellPrice: 30 },
  6: { name: "Oak log", itemId: 6, vendorSellPrice: 13 },
  7: { name: "Maple log", itemId: 7, vendorSellPrice: 16 },
  8: { name: "Teak log", itemId: 8, vendorSellPrice: 20 },
  9: { name: "Mahagony log", itemId: 9, vendorSellPrice: 40 },
  10: { name: "Yew log", itemId: 10, vendorSellPrice: 55 },
  28: { name: "Tin ore", itemId: 28, vendorSellPrice: 5 },
  29: { name: "Copper ore", itemId: 29, vendorSellPrice: 5 },
  30: { name: "Iron ore", itemId: 30, vendorSellPrice: 8 },
  31: { name: "Coal", itemId: 31, vendorSellPrice: 11 },
  32: { name: "Silver ore", itemId: 32, vendorSellPrice: 15 },
  33: { name: "Gold ore", itemId: 33, vendorSellPrice: 52 },
  39: { name: "Platinum ore", itemId: 39, vendorSellPrice: 62 },
  41: { name: "Meteroit ore", itemId: 41, vendorSellPrice: 105 },
  42: { name: "Titanium ore", itemId: 42, vendorSellPrice: 155 },
  45: { name: "Meteroit bar", itemId: 45, vendorSellPrice: 345 },
  46: { name: "Titanium bar", itemId: 46, vendorSellPrice: 650 },
  51: { name: "Bronze helmet", itemId: 51, vendorSellPrice: 32 },
  57: { name: "Iron helmet", itemId: 57, vendorSellPrice: 32 },
  63: { name: "Steel helmet", itemId: 63, vendorSellPrice: 72 },
  77: { name: "Platinum helmet", itemId: 77, vendorSellPrice: 780 },
  81: { name: "Meteroit bodyplate", itemId: 81, vendorSellPrice: 6_200 },
  110: { name: "Raw meet", itemId: 110, vendorSellPrice: 20 },
  126: { name: "Potato seeds", itemId: 126, vendorSellPrice: 7 },
  127: { name: "Carrot seeds", itemId: 127, vendorSellPrice: 10 },
  128: { name: "Tomato seeds", itemId: 128, vendorSellPrice: 15 },
  129: { name: "Cabbage seeds", itemId: 129, vendorSellPrice: 15 },
  130: { name: "Strawberry seeds", itemId: 130, vendorSellPrice: 30 },
  131: { name: "Watermelon seeds", itemId: 131, vendorSellPrice: 60 },
  162: { name: "Cooked pufferfish", itemId: 162, vendorSellPrice: 34 },
  275: { name: "Cursed flax", itemId: 275, vendorSellPrice: 34 },
  400: { name: "Grape seeds", itemId: 400, vendorSellPrice: 80 },
  402: { name: "Papaya seeds", itemId: 402, vendorSellPrice: 100 },
  404: { name: "Dragon fruit seeds", itemId: 404, vendorSellPrice: 125 },
  406: { name: "Redwood log", itemId: 406, vendorSellPrice: 75 },
  407: { name: "Magical log", itemId: 407, vendorSellPrice: 110 },
  587: { name: "Magical plank", itemId: 587, vendorSellPrice: 210 },
};

export const isWhiteListed = (itemId: number): boolean => {
  return allowedItems[itemId] !== undefined;
};
